### ISSUE TITLE
Any reason using MATLAB instead of Python?

### ISSUE THREAD

**Issue by FL-CFD** [ideas-um/FAST#53]
Very appreciate the effort to make this valuable project open source. I am just curious whether there are any reason to use MATLAB instead of Python?

**Comment by prmoko** [comment]
Hello, @FL-CFD, thank you for reaching out! We're glad to hear that you appreciate our efforts, and hope you are finding FAST to be useful. There are a few reasons that we chose to use Matlab instead of Python:

1. First, the contract that FAST was released under requested that Matlab be used (see the bottom of our README for more information about this).
2. Second, we had a legacy aircraft sizing code in Matlab already from previous research endeavors, so we wanted to leverage that in our development of FAST.
3. Most of the University of Michigan (where we're based) students are more familiar with Matlab than Python, which makes it easier to deploy FAST in a classroom environment.

I hope this information helps! I'm going to close this issue, but feel free to open it back up if you have more questions

**Comment by FL-CFD** [comment]
it helps. Thank you for this explanation.

**Comment by FL-CFD** [comment]
> Hello, @FL-CFD, thank you for reaching out! We're glad to hear that you appreciate our efforts, and hope you are finding FAST to be useful. There are a few reasons that we chose to use Matlab instead of Python:
> 
>     1. First, the contract that FAST was released under requested that Matlab be used (see the bottom of our README for more information about this).
> 
>     2. Second, we had a legacy aircraft sizing code in Matlab already from previous research endeavors, so we wanted to leverage that in our development of FAST.
> 
>     3. Most of the University of Michigan (where we're based) students are more familiar with Matlab than Python, which makes it easier to deploy FAST in a classroom environment.
> 
> 
> I hope this information helps! I'm going to close this issue, but feel free to open it back up if you have more questions
it helps. Thank you for this explanation.
